### PR TITLE
comma added in embetter/text/__init_.py fixes #101

### LINKED ISSUE #101: add a comma in __all__ section of  `/home/runner/work/embetter/embetter/embetter/text/__init__.py`
also I would like to know how to prevent this from happenig in the future, I've run the tests, but they clearly don't cover that, also the checks don't happen during a commit (As in scikit-learn) so I could definitely use some hint on how to check if there's no bug in the code I commit

### PR DESCRIPTION
**Pull request by anopsy**
fixed the comma
btw
I was curious about the ruff pre-commit hooks. You have that in sklego, I wondered why not here. I mean if there is a reason or just not yet. If not yet, then that might be something I would like to try to do.

### CODE REVIEW

**Comment by koaning** [comment]
Francesco added ruff on sklego. Given that I have a busy busy busy life I prefer not to make changes to my repos unless I really need to. Flake8 works fine, ruff is just a bit faster. 

Thanks for the PR!

**Comment by anopsy** [comment]
Oh I see. Btw, do I see correctly that the unit tests failed on this PR?
=========================== short test summary info ============================
FAILED tests/test_text.py::test_basic_bpemb[both] - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 40762: invalid start byte

I run the tests in pytests and all passed. Also checked the files locally with Black. I wonder what happened here?

**Comment by koaning** [comment]
The checks look green on your PR, no? 

CleanShot 2024-04-26 at 22 27 10@2x

**Comment by anopsy** [comment]
I could have screenshoted it, I saw red on unittest, but now it's green. Now I wonder even more. 😅 Anyway, I'm happy it's all good now😊

**Comment by anopsy** [comment]
> Francesco added ruff on sklego. Given that I have a busy busy busy life I prefer not to make changes to my repos unless I really need to. Flake8 works fine, ruff is just a bit faster.

Just to clarify, I meant the lack of pre-commits in general. I can't see neither ruff nor Flake8 as the pre-commit hooks. When I was committing: 
- I didn't see any checks from flake8 happening (unless it's happening under the hood) , 
- Flake8 didn't catch that missing comma, 
- I also don't see the pre-commit-config.yaml in the repo. I see there's .flake8 file, but I'm not sure at what point he checks the code.

**Comment by koaning** [comment]
Ah like that! I think the main reason why these are missing is because the embetter repo really only has one author (me) and I've sofar managed fine by running most of these things locally. Locally I usually do that by running `make check` which runs all of my checks. 

You'd certainly be welcome to add these to the repo if you'd enjoy the exercise by the way, it's just that this is one of the plugins that I made in a hurry and never really took the effort to make the project more appropriate for a "multi-author" situation. Scikit-lego was multi-author from the start so we took more time into the developer experience there.

**Comment by anopsy** [comment]
yeah I noticed that you're the only contributor and thought that probably embetter was a just a little convenient tool. Anyway I would love to add the hooks. Thank you clarifying

**Comment by anopsy** [comment]
what do we want? flake8, black or ruff?

**Comment by koaning** [comment]
ruff should be fine!



*- Vincent*

**Pull request merged**
