### PR TITLE
[WIP] Feature/progress bar

### PR DESCRIPTION
**Pull request by CarloLepelaars**
Fixes issue #20 

- [x] Adds progress bar to all text and image embedders.
- [x] Tests for `SentenceEncoder`.
- [ ] Use [perfplot](https://calmcode.io/shorts/perfplot.html) for progress bar?
- [ ] Can we ensure fast NumPy vectorization while using a progress bar?

### CODE REVIEW

**Comment by koaning** [comment]
One thing that I'm also wondering is... Technically nothing is stopping you from doing something like this: 

```python
tfm = SentenceTransformer()
tfm.transform([t for t in tqdm(long_list_of_texts)])
```

It's not a huge ask from an end user to do this, and it might just be enough to add an FAQ on the docs for this.

**Comment by CarloLepelaars** [comment]
Agree, if you are iterating one by one the user can easily add a progress bar and configure it as they like. 

I'm not that familiar with mkdocs, but can have a look on integrating a perfplot in the docs.

**Comment by koaning** [comment]
There's a course on calmcode 😉

**Comment by CarloLepelaars** [comment]
Calmcode saves the day, as usual! 😁

**Comment by CarloLepelaars** [comment]
Closing this to avoid introducing unnecessary complexity and slow down these encoders.

**Pull request closed without merging**
